In [1]:
import numpy as np
pred_label = np.array([0,1,1,2])
gt_label = np.array([1,1,1,1])

lb_max = np.max((pred_label, gt_label))

In [2]:
lb_max

2

In [9]:
import math
gt_label = np.array([-1,1,0,1,0,1])
mask = gt_label >= 0
mask

array([False,  True,  True,  True,  True,  True])

In [11]:
gt_label[mask]

array([1, 0, 1, 0, 1])

In [16]:
x = np.array([1,3,3,4,5,4,7])
x_True_False1 = np.array([True,True,True,True,True,True,True])
x1 = x[x_True_False1]	# [3 3 4 5 4 7]
x_True_False2 = np.array([True,True,True,True,True,True,True])
x = x[x_True_False2]
print(x)                # [1 3 3 4 5 4 7]

y = np.bincount(x)      # 返回从0到输入array中最大值 每个数出现的次数
print(y)                # [0 1 0 2 2 1 0 1]
z = np.bincount(x, minlength=9)     # minlength限制返回列表的最小长度，长度不够，0来凑
print(z)                # [0 1 0 2 2 1 0 1 0]
print(z.reshape(3,3))

[1 3 3 4 5 4 7]
[0 1 0 2 2 1 0 1]
[0 1 0 2 2 1 0 1 0]
[[0 1 0]
 [2 2 1]
 [0 1 0]]


In [13]:
x = np.array([1,3,3,4,5,4,7])
x_label = np.array([1,3,3,4,5,5,7])     # 假设有10类
print(np.bincount(10*x.astype(int)+x_label, minlength=10**2).reshape(10,10))

[[0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 2 0 0 0 0 0 0]
 [0 0 0 0 1 1 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]
